{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ServiceAccount*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.labels.app }}*/}}
{{/*  labels:*/}}
{{/*    {{- range $key, $val := .Values.labels }}*/}}
{{/*      {{ $key }}: "{{ $val }}"*/}}
{{/*      {{- end }}*/}}
